# ./docker-dev/docker-compose.yml
# 开发环境配置
version: '3.8'

services:
  # MySQL 数据库服务 - 开发环境
  mysql-dev:
    image: mysql:8
    container_name: mysql-dev
    ports:
      - "3306:3306" # 开发环境使用3307端口，避免与本地MySQL冲突
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - mysql_dev_data:/var/lib/mysql
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - micro-forum-dev-net
    deploy:
      resources:
        limits:
          memory: 300M # 开发环境可以降低内存限制

  # Redis 缓存服务 - 开发环境
  redis-dev:
    image: redis:6.2.19-alpine
    container_name: redis-dev
    ports:
      - "6379:6379" # 开发环境开放Redis端口，方便调试
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_dev_data:/data
    networks:
      - micro-forum-dev-net
    command: [ "redis-server", "--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru" ]
    deploy:
      resources:
        limits:
          memory: 50M

  # Spring Boot 后端服务 - 开发环境
  micro-forum-server-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro-forum-server-dev
    ports:
      - "8080:8080" # 开发环境直接暴露端口，方便调试
    environment:
      SPRING_PROFILES_ACTIVE: docker-dev # 激活Docker开发环境配置
      # 数据库配置
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # Redis配置
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # JWT配置
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      # 邮箱配置
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      # JVM配置
      JAVA_OPTS: "-Xmx256m -Xms128m -XX:MaxMetaspaceSize=64m -Dspring.devtools.restart.enabled=true"
    volumes:
      - micro_forum_dev_logs:/app/logs
      - micro_forum_dev_uploads:/opt/app-data/micro-forum/uploads
      # 开发环境可以挂载源码目录，支持热重载
      - ../src:/app/src:ro
    networks:
      - micro-forum-dev-net
    depends_on:
      - mysql-dev
      - redis-dev
    deploy:
      resources:
        limits:
          memory: 256M

  # Nginx 反向代理服务 - 开发环境
  nginx-dev:
    image: nginx:1.28.0-alpine
    container_name: nginx-dev
    ports:
      - "80:80"
      - "443:443" # 开发环境也可以配置HTTPS
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/html:/usr/share/nginx/html"
      - micro_forum_dev_uploads:/usr/share/nginx/html/uploads
    depends_on:
      - micro-forum-server-dev
    networks:
      - micro-forum-dev-net
    deploy:
      resources:
        limits:
          memory: 30M

# 开发环境网络
networks:
  micro-forum-dev-net:
    name: micro-forum-dev-network

# 开发环境数据卷
volumes:
  mysql_dev_data:
  redis_dev_data:
  micro_forum_dev_logs:
  micro_forum_dev_uploads:
